### PR TITLE
Feat 103 filter by year

### LINKED ISSUE #103: Scalability and cost effectiveness

### PR DESCRIPTION
**Pull request by eurolife**
UI for year range filtering is completed. User can drag from left or right to set a year range. Min and max years shown below range slider. 

This does not close #103 as API work still needs to be done.

### CODE REVIEW

**Comment by kdutia** [comment]
@eurolife - I seem to be able to cross the values over, so `a>b`. This isn't ideal if `a=minYear` and `b=maxYear`. Is there any way to ensure that `a<=b`? 

image

**Comment by eurolife** [comment]
@kdutia 
Hmm. That may require some time to figure out. I wonder if we keep a new open issue to handle later and just make sure that during the demo Michal doesn't cross them over each other?
Also, you seem to not have the latest version of that because I removed the --a and --b: and moved the years below the slider. It should look more like this
Screenshot 2021-10-27 at 11 49 38

**Comment by kdutia** [comment]
Cool @eurolife. Happy to approve as long as @chrisaballard is happy. Would you mind making the new issue and mentioning it in the current issue pls?

**Review by kdutia — APPROVED** [review]
looks good, as long as new issue for preventing swapping of min and max is created

**Comment by eurolife** [comment]
@kdutia Yep will do. I'll mention it and create the new issue before merging this.

**Pull request merged**
