### PR TITLE
Feat 129 change to search api

### PR DESCRIPTION
**Pull request by eurolife**
Three issues are combined into this PR as they were relatively small.

#129 On initial load, the search api is called without a query and returns a set of results.

#50 Text keyword matches are no longer highlighted in full text pages since it is no longer an exact match result.

#132 Clicking X in search box will now clear search query. Also fixed a number of other small issues including existing geography filters being ignored on clearing search, another issue where multiple geography filters stopped working, and another issue where no results message wasn't displaying when a geography filter yielded no results.

### CODE REVIEW

**Comment by kdutia** [comment]
@eurolife I'm getting the following error when clicking on full-text view for an item and then going back to search, from the start page, which shows documents alphabetically. Do you get this on your machine?

image

Another thing I've noticed is that if I enter a search term, then click to full-text view for a page, then go back to the search results, my query is hidden - I see `What are you looking for?`. Functionally this is ok as I can still click on the search bar to get my current query, but would it be possible to disable hiding the query in this instance?

**Comment by kdutia** [comment]
After a chat with @eurolife, I've raised the point around the query being hidden as issue

* #62

**Review by kdutia — APPROVED** [review]
Looks great! 👏🏽👏🏽👏🏽 I also connected the new issue #62 to this.

**Comment by eurolife** [comment]
Fixed error and also #62 , user should now still be able to see their search query when returning to the search results page.

**Pull request merged**
